<?php

/**
 * BaseTaxRate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property decimal $tax_rate
 * @property decimal $start_bracket
 * 
 * @method integer getId()            Returns the current record's "id" value
 * @method decimal getTaxRate()       Returns the current record's "tax_rate" value
 * @method decimal getStartBracket()  Returns the current record's "start_bracket" value
 * @method TaxRate setId()            Sets the current record's "id" value
 * @method TaxRate setTaxRate()       Sets the current record's "tax_rate" value
 * @method TaxRate setStartBracket()  Sets the current record's "start_bracket" value
 * 
 * @package    meteb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaxRate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tax_rate');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('tax_rate', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 5,
             'length' => 10,
             ));
        $this->hasColumn('start_bracket', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 5,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}