<?php

/**
 * BasePri
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property decimal $value
 * @property Doctrine_Collection $Quote
 * 
 * @method integer             getId()    Returns the current record's "id" value
 * @method decimal             getValue() Returns the current record's "value" value
 * @method Doctrine_Collection getQuote() Returns the current record's "Quote" collection
 * @method Pri                 setId()    Sets the current record's "id" value
 * @method Pri                 setValue() Sets the current record's "value" value
 * @method Pri                 setQuote() Sets the current record's "Quote" collection
 * 
 * @package    meteb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePri extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pri');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('value', 'decimal', 15, array(
             'type' => 'decimal',
             'scale' => 3,
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Quote', array(
             'local' => 'id',
             'foreign' => 'pri_id'));
    }
}