<?php

/**
 * BaseQuoteOutputTypeValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $quote_id
 * @property integer $quote_output_type_id
 * @property string $value
 * @property Quote $Quote
 * @property QuoteOutputType $QuoteOutputType
 * 
 * @method integer              getId()                   Returns the current record's "id" value
 * @method integer              getQuoteId()              Returns the current record's "quote_id" value
 * @method integer              getQuoteOutputTypeId()    Returns the current record's "quote_output_type_id" value
 * @method string               getValue()                Returns the current record's "value" value
 * @method Quote                getQuote()                Returns the current record's "Quote" value
 * @method QuoteOutputType      getQuoteOutputType()      Returns the current record's "QuoteOutputType" value
 * @method QuoteOutputTypeValue setId()                   Sets the current record's "id" value
 * @method QuoteOutputTypeValue setQuoteId()              Sets the current record's "quote_id" value
 * @method QuoteOutputTypeValue setQuoteOutputTypeId()    Sets the current record's "quote_output_type_id" value
 * @method QuoteOutputTypeValue setValue()                Sets the current record's "value" value
 * @method QuoteOutputTypeValue setQuote()                Sets the current record's "Quote" value
 * @method QuoteOutputTypeValue setQuoteOutputType()      Sets the current record's "QuoteOutputType" value
 * 
 * @package    meteb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuoteOutputTypeValue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quote_output_type_value');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('quote_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('quote_output_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Quote', array(
             'local' => 'quote_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('QuoteOutputType', array(
             'local' => 'quote_output_type_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}