<?php

/**
 * BaseQuotehistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $client_id
 * @property integer $created_by
 * @property sfGuardUser $Client
 * @property sfGuardUser $Parent
 * 
 * @method integer      getId()         Returns the current record's "id" value
 * @method integer      getClientId()   Returns the current record's "client_id" value
 * @method integer      getCreatedBy()  Returns the current record's "created_by" value
 * @method sfGuardUser  getClient()     Returns the current record's "Client" value
 * @method sfGuardUser  getParent()     Returns the current record's "Parent" value
 * @method Quotehistory setId()         Sets the current record's "id" value
 * @method Quotehistory setClientId()   Sets the current record's "client_id" value
 * @method Quotehistory setCreatedBy()  Sets the current record's "created_by" value
 * @method Quotehistory setClient()     Sets the current record's "Client" value
 * @method Quotehistory setParent()     Sets the current record's "Parent" value
 * 
 * @package    meteb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuotehistory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quotehistory');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('created_by', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Client', array(
             'local' => 'client_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Parent', array(
             'local' => 'created_by',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}