<?php

/**
 * BaseMarketdata
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $uploaded_at
 * @property timestamp $inception_date
 * @property string $month_array
 * @property string $discounting_array
 * @property string $dhfactors_matrix
 * 
 * @method integer    getId()                Returns the current record's "id" value
 * @method timestamp  getUploadedAt()        Returns the current record's "uploaded_at" value
 * @method timestamp  getInceptionDate()     Returns the current record's "inception_date" value
 * @method string     getMonthArray()        Returns the current record's "month_array" value
 * @method string     getDiscountingArray()  Returns the current record's "discounting_array" value
 * @method string     getDhfactorsMatrix()   Returns the current record's "dhfactors_matrix" value
 * @method Marketdata setId()                Sets the current record's "id" value
 * @method Marketdata setUploadedAt()        Sets the current record's "uploaded_at" value
 * @method Marketdata setInceptionDate()     Sets the current record's "inception_date" value
 * @method Marketdata setMonthArray()        Sets the current record's "month_array" value
 * @method Marketdata setDiscountingArray()  Sets the current record's "discounting_array" value
 * @method Marketdata setDhfactorsMatrix()   Sets the current record's "dhfactors_matrix" value
 * 
 * @package    meteb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMarketdata extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('marketdata');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('uploaded_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('inception_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('month_array', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('discounting_array', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('dhfactors_matrix', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}