<?php

/**
 * BaseActivityType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property Doctrine_Collection $Activity
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getTitle()    Returns the current record's "title" value
 * @method Doctrine_Collection getActivity() Returns the current record's "Activity" collection
 * @method ActivityType        setId()       Sets the current record's "id" value
 * @method ActivityType        setTitle()    Sets the current record's "title" value
 * @method ActivityType        setActivity() Sets the current record's "Activity" collection
 * 
 * @package    meteb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivityType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('activity_type');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Activity', array(
             'local' => 'id',
             'foreign' => 'activitytype_id'));
    }
}