<?php

/**
 * BaseExpensedata
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $renewal_expenses
 * @property string $expense_inflation
 * @property string $initial_expenses
 * @property string $loadings
 * 
 * @method integer     getId()                Returns the current record's "id" value
 * @method string      getRenewalExpenses()   Returns the current record's "renewal_expenses" value
 * @method string      getExpenseInflation()  Returns the current record's "expense_inflation" value
 * @method string      getInitialExpenses()   Returns the current record's "initial_expenses" value
 * @method string      getLoadings()          Returns the current record's "loadings" value
 * @method Expensedata setId()                Sets the current record's "id" value
 * @method Expensedata setRenewalExpenses()   Sets the current record's "renewal_expenses" value
 * @method Expensedata setExpenseInflation()  Sets the current record's "expense_inflation" value
 * @method Expensedata setInitialExpenses()   Sets the current record's "initial_expenses" value
 * @method Expensedata setLoadings()          Sets the current record's "loadings" value
 * 
 * @package    meteb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExpensedata extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('expensedata');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('renewal_expenses', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('expense_inflation', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('initial_expenses', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('loadings', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}