<?php

/**
 * BaseQuoteType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property Doctrine_Collection $Quote
 * 
 * @method integer             getId()    Returns the current record's "id" value
 * @method string              getTitle() Returns the current record's "title" value
 * @method Doctrine_Collection getQuote() Returns the current record's "Quote" collection
 * @method QuoteType           setId()    Sets the current record's "id" value
 * @method QuoteType           setTitle() Sets the current record's "title" value
 * @method QuoteType           setQuote() Sets the current record's "Quote" collection
 * 
 * @package    meteb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuoteType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quote_type');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Quote', array(
             'local' => 'id',
             'foreign' => 'quote_type_id'));
    }
}