<?php

/**
 * BaseMortalityRate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $age
 * @property decimal $mortality_male
 * @property decimal $mortality_female
 * 
 * @method integer       getId()               Returns the current record's "id" value
 * @method integer       getAge()              Returns the current record's "age" value
 * @method decimal       getMortalityMale()    Returns the current record's "mortality_male" value
 * @method decimal       getMortalityFemale()  Returns the current record's "mortality_female" value
 * @method MortalityRate setId()               Sets the current record's "id" value
 * @method MortalityRate setAge()              Sets the current record's "age" value
 * @method MortalityRate setMortalityMale()    Sets the current record's "mortality_male" value
 * @method MortalityRate setMortalityFemale()  Sets the current record's "mortality_female" value
 * 
 * @package    meteb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMortalityRate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mortality_rate');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('age', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mortality_male', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 5,
             'length' => 10,
             ));
        $this->hasColumn('mortality_female', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 5,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}