<?php

/**
 * BaseClientStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property Doctrine_Collection $UserProfile
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getTitle()       Returns the current record's "title" value
 * @method Doctrine_Collection getUserProfile() Returns the current record's "UserProfile" collection
 * @method ClientStatus        setId()          Sets the current record's "id" value
 * @method ClientStatus        setTitle()       Sets the current record's "title" value
 * @method ClientStatus        setUserProfile() Sets the current record's "UserProfile" collection
 * 
 * @package    meteb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClientStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client_status');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserProfile', array(
             'local' => 'id',
             'foreign' => 'status_id'));
    }
}