<?php

/**
 * BaseQuotehistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $client_id
 * @property integer $financialadvisor_id
 * 
 * @method integer      getId()                  Returns the current record's "id" value
 * @method integer      getClientId()            Returns the current record's "client_id" value
 * @method integer      getFinancialadvisorId()  Returns the current record's "financialadvisor_id" value
 * @method Quotehistory setId()                  Sets the current record's "id" value
 * @method Quotehistory setClientId()            Sets the current record's "client_id" value
 * @method Quotehistory setFinancialadvisorId()  Sets the current record's "financialadvisor_id" value
 * 
 * @package    meteb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuotehistory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quotehistory');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('financialadvisor_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}