<?php

/**
 * BaseQuoteOutputType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property Doctrine_Collection $QuoteOutputTypeValue
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getTitle()                Returns the current record's "title" value
 * @method Doctrine_Collection getQuoteOutputTypeValue() Returns the current record's "QuoteOutputTypeValue" collection
 * @method QuoteOutputType     setId()                   Sets the current record's "id" value
 * @method QuoteOutputType     setTitle()                Sets the current record's "title" value
 * @method QuoteOutputType     setQuoteOutputTypeValue() Sets the current record's "QuoteOutputTypeValue" collection
 * 
 * @package    meteb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuoteOutputType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quote_output_type');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('QuoteOutputTypeValue', array(
             'local' => 'id',
             'foreign' => 'quote_output_type_id'));
    }
}