<?php

/**
 * BaseTaxRebate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $age
 * @property integer $rebate
 * 
 * @method integer   getId()     Returns the current record's "id" value
 * @method integer   getAge()    Returns the current record's "age" value
 * @method integer   getRebate() Returns the current record's "rebate" value
 * @method TaxRebate setId()     Sets the current record's "id" value
 * @method TaxRebate setAge()    Sets the current record's "age" value
 * @method TaxRebate setRebate() Sets the current record's "rebate" value
 * 
 * @package    meteb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaxRebate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tax_rebate');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('age', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rebate', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}