quote:
  class: sfDoctrineRouteCollection
  options:
    model:                Quote
    module:               quote
    prefix_path:          /quote
    column:               id
    with_wildcard_routes: true

#profile
profile:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               profile
    prefix_path:          /profile
    column:               id
    with_wildcard_routes: true

#quote
quote_new:
  url:     /quote/new.:sf_format
  class:   sfDoctrineRoute
  options: { model: Quote, type: object }
  param:   { module: quote, action: new, sf_format: html }
  requirements: { sf_method: get }
  
quote_edit:
  url:     /quote/:id/edit.:sf_format
  class:   sfDoctrineRoute
  options: { model: Quote, type: object }
  param:   { module: quote, action: edit, sf_format: html }
  requirements: { sf_method: get }

#advisor
advisor:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               advisor
    prefix_path:          /advisor
    column:               id
    with_wildcard_routes: true

#client
client:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               client
    prefix_path:          /client
    column:               id
    with_wildcard_routes: true
  
#user_profile
user_profile:
  class: sfDoctrineRouteCollection
  options:
    model:                UserProfile
    module:               userprofile
    prefix_path:          /userprofile
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: dashboard, action: index }
  
userprofile:
  url:   /Userprofiles
  param: { module: userprofile, action: index }

userprofile_profile:
  class: sfDoctrineRouteCollection
  options:
    model:                UserProfile
    module:               userprofile
    prefix_path:          userprofile
    column:               id
    with_wildcard_routes: true

signout:
  url:   /Sign-Out
  param: { module: dashboard, action: index }