# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
all:
 # because by default every filter condition is true, we have to set this var
 # to off in all other environments
 enable_soap_parameter: off

# your environment for webservice mode
 soap:
  # enable the `ckSoapParameterFilter`
  enable_soap_parameter: on
  ck_web_service_plugin:
    # the location of your wsdl file
    wsdl: %SF_DATA_DIR%/wsdl/SOAPApi.wsdl
    # the class that will be registered as handler for webservice requests
    handler: SOAPApiHandler
    persist: <?php echoln('SOAP_PERSISTENCE_SESSION') ?>
    soap_options:
      encoding: utf-8
      soap_version: <?php echoln('SOAP_1_2') ?>

      # mapping of wsdl types to PHP types
      classmap:
        CreateClientRequest:            CreateClientRequest
        CreateClientResponse:           ckGenericArray
        CreateQuoteRequest:             CreateQuoteRequest
        CreateQuoteResponse:            ckGenericArray

    soap_headers:
          AuthHeader:
            class: AuthData