# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

#api
api_new_login:
  url:   /login/new/:token/:username/:password.:sf_format
  param: { module: login, action: new }
  requirements:
    token:      \w+
    username:   \w+
    password:   \w+
    sf_format: (?:xml|json|yaml)
    sf_method: [get, post]

api_client_list:
  url:   /clients/:token.:sf_format
  param: { module: client, action: list }
  requirements:
    sf_format: (?:xml|json|yaml)
    sf_method: [get]

api_new_create:
  url: /clients/new/:token.:sf_format
  param: { module: client, action: new }
  requirements:
    sf_format: (?:xml|json|yaml)
    sf_method: [post]
      
api_new_quote:
  url:   /quotes/new/:token.:sf_format
  param: { module: quote, action: new }
  requirements:
    clientid:   \w+
    sf_format: (?:xml|json|yaml)
    sf_method: [get, post]
    
wsdl:
  url:   /:service.wsdl
  param: { module: wsdl, action: index }