generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          client
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
       display: [ first_name, last_name, email_address ]
       title: 'Clients'
       batch_actions:
         disable:     ~
         enable:      ~
         newQuote:    ~
       object_actions:
         _edit:       ~
         disable:     ~
         newQuote:    ~
      filter:
        class: false
      form:
        class:     BackendClientForm
      edit:    ~
      new:     ~
