<?php

/**
 * Activity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    meteb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: ActivityClass.php 7490 2010-03-29 19:53:27Z swentzel $
 */
class Activity extends BaseActivity
{
}