<?php

/**
 * ClientStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientStatus');
    }
}