<?php

/**
 * CommissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Commission');
    }
}