<?php

/**
 * ExpensedataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExpensedataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExpensedataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Expensedata');
    }
}