<?php

/**
 * MortalityRateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MortalityRateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MortalityRateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MortalityRate');
    }
    

	/** 
	 *	This function retrieves the mortality rates from the database
	 *	The mortality rates are in the form of a table of male and female rates sorted by age
	 *	The PA90-1 tables were used
	 *
	 * @param unknown_type $upload_date
	 * @param unknown_type $inception_date
	 * @param unknown_type $month_array
	 * @param unknown_type $discounting_array
	 * @param unknown_type $dhfactors_matrix
	 * 
	 * @return array Array of Mortality Rates for calculation
	 */	
	public function get_mortality_rates()
	{
		$mortalityResult = array();
		
		$q = Doctrine_Query::create()
		   ->from('MortalityRate mr');		
		     
		$mortalityData = $q->fetchArray(); 
		
		foreach($mortalityData as $key => $value){
			$mortalityResult[$key]['1'] = $value['mortality_male'];
			$mortalityResult[$key]['2'] = $value['mortality_female'];
		}
		
		return $mortalityResult;
	}
}