<?php

/**
 * MortalityRateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MortalityRateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MortalityRateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MortalityRate');
    }
}