<?php

/**
 * QuoteOutputTypeValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuoteOutputTypeValueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuoteOutputTypeValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuoteOutputTypeValue');
    }
}