<?php

/**
 * QuotehistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuotehistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuotehistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Quotehistory');
    }
}