<?php

/**
 * QuoteTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuoteTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuoteTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuoteType');
    }
}