<?php

/**
 * SpouseReversionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpouseReversionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpouseReversionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SpouseReversion');
    }
}