<?php

/**
 * TaxRebateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxRebateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxRebateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaxRebate');
    }
    
    /**
     * Function to return all Tax Rebates
     *
     * @return array Tax Rebates
     */
	public function get_tax_rebates()
	{
	//This function retrieves the tax rates from the database
	//These tax rates will need to be updated every year. The tax rates are valid from 1 March until 28 Feb of the next year.

		$place=0;
		$tax_rebates = array();
		
		$q = Doctrine_Query::create()
		   ->from('Taxrebate tr');		
		     
		$taxrebateData = $q->fetchArray(); 
		
		foreach($taxrebateData as $taxrebate)
		{
			$tax_rebates[$place][1] = $taxrebate['age'];
			$tax_rebates[$place][2] = $taxrebate['rebate'];
			$place++;
		}

		return $tax_rebates;
	}
}