<?php

/**
 * TaxRateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxRateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxRateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaxRate');
    }
    
    /**
     * Returns all tax rates
     *
     * @return array Tax Rebates
     */
	public function get_tax_rates()
	{
	//This function retrieves the tax rates from the database
	//These tax rates will need to be updated every year. The tax rates are valid from 1 March until 28 Feb of the next year.

		$place=0;
		$tax_rates = array();
		
		$q = Doctrine_Query::create()
		   ->from('Taxrate tr');		
		     
		$taxrateData = $q->fetchArray(); 
		
		foreach($taxrateData as $taxrate)
		{
			$tax_rates[$place][1] = $taxrate['tax_rate'];
			$tax_rates[$place][2] = $taxrate['start_bracket'];
			$place++;
		}

		return $tax_rates;
	}
}