<?php

/**
 * UserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    meteb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserProfile extends BaseUserProfile
{
  /**
  * Function to save a UserProfile Object
  * 
  * @param void
  * @return boolean If the save was successful
  */
  public function save(Doctrine_Connection $conn = null)
  {
    if (!$this->getToken())
    {
      $this->setToken(sha1($this->getIdnumber().time().rand(11111, 99999)));
    }
 
    return parent::save($conn);
  }
}