<?php

/**
 * UserProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserProfile');
    }
}