<?php

/**
 * UserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    meteb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserProfile extends BaseUserProfile
{
	/**
	 * Function to extend the Save function of the User Profile Class
	 * 
	 * @param 
	 * 
	 * @return UserProfile UserProfile Object
	 */	
	 public function save(Doctrine_Connection $conn = null)
	 {		
		$result = parent::save();
		
		Activity::addActivty('',1,'');
		
		return $result;
	 }
}