# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  datagrid:
    jsframwork: jquery # prototype or jquery 
    
dev:
  url:
   backend: http://meteb.localhost/backend.php
   
prod:
  url:
   backend: http://ebannuities.co.za/backend.php