#profile
profile:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               profile
    prefix_path:          /profile
    column:               id
    with_wildcard_routes: true
  
#advisor 
advisor:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               advisor
    prefix_path:          /advisor
    column:               id
    with_wildcard_routes: true
    
#client 
client:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               client
    prefix_path:          /client
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /Homepage/
  param: { module: home, action: index }
  
default:
  url:   /
  param: { module: sfGuardAuth, action: signin }
  
signout:
  url:   /
  param: { module: sfGuardAuth, action: signin }
  

