# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /Homepage/
  param: { module: home, action: index }
  
default:
  url:   /
  param: { module: sfGuardAuth, action: signin }
  
signout:
  url:   /
  param: { module: sfGuardAuth, action: signin }
  
#client
client_index:
  url:     /clients
  param:   { module: client, action: index }
  requirements: { sf_method: get }
  
client_new:
  url:     /client/new
  param:   { module: client, action: new }
  requirements: { sf_method: get }
  
client_create:
  url:     /client.:sf_format
  class:   sfDoctrineRoute
  options: { model: UserProfile, type: object }
  param:   { module: client, action: create, sf_format: html }
  requirements: { sf_method: post }
  
client_show:
  url:     /client/show.:sf_format
  class:   sfDoctrineRoute
  options: { model: UserProfile, type: object }
  param:   { module: client, action: edit, sf_format: html }
  requirements: { sf_method: post }
  
client_edit:
  url:     /client/edit.:sf_format
  class:   sfDoctrineRoute
  options: { model: UserProfile, type: object }
  param:   { module: client, action: edit, sf_format: html }
  requirements: { sf_method: post }
  
client_delete:
  url:     /client/delete.:sf_format
  class:   sfDoctrineRoute
  options: { model: UserProfile, type: object }
  param:   { module: client, action: delete, sf_format: html }
  requirements: { sf_method: post }
  
#advisor
advisor_index:
  url:     /advisors
  param:   { module: advisor, action: index }
  requirements: { sf_method: get }
  
advisor_new:
  url:     /advisor/new
  param:   { module: advisor, action: new }
  requirements: { sf_method: get }
  
advisor_create:
  url:     /advisor.:sf_format
  class:   sfDoctrineRoute
  options: { model: UserProfile, type: object }
  param:   { module: advisor, action: create, sf_format: html }
  requirements: { sf_method: post }
  
advisor_show:
  url:     /advisor/show.:sf_format
  class:   sfDoctrineRoute
  options: { model: UserProfile, type: object }
  param:   { module: advisor, action: edit, sf_format: html }
  requirements: { sf_method: post }
  
advisor_edit:
  url:     /advisor/edit.:sf_format
  class:   sfDoctrineRoute
  options: { model: UserProfile, type: object }
  param:   { module: advisor, action: edit, sf_format: html }
  requirements: { sf_method: post }
  
advisor_delete:
  url:     /advisor/delete.:sf_format
  class:   sfDoctrineRoute
  options: { model: UserProfile, type: object }
  param:   { module: advisor, action: delete, sf_format: html }
  requirements: { sf_method: post }