#quote
quote:
  class: sfDoctrineRouteCollection
  options:
    model:                Quote
    module:               quote
    prefix_path:          /quote
    column:               id
    with_wildcard_routes: true

quote_new:
  url:     /quote/new.:sf_format
  class:   sfDoctrineRoute
  options: { model: Quote, type: object }
  param:   { module: quote, action: new, sf_format: html }
  requirements: { sf_method: get }


quote_edit:
  url:     /quote/:id/edit.:sf_format
  class:   sfDoctrineRoute
  options: { model: Quote, type: object }
  param:   { module: quote, action: edit, sf_format: html }
  requirements: { sf_method: get }

quote_new_user:
  url:     /New-Quote-For/:id.:sf_format
  class:   sfDoctrineRoute
  options: { model: sfGuardUser, type: object }
  param:   { module: quote, action: new, sf_format: html }
  requirements: { sf_method: get }

quote_pdf:
  url:     /Quote-PDF/:id
  class:   sfDoctrineRoute
  options: { model: Quote, type: object }
  param:   { module: quote, action: pdf, sf_format: html }
  requirements: { sf_method: get }

#profile
profile:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               profile
    prefix_path:          /profile
    column:               id
    with_wildcard_routes: true
    
#client 
client:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               client
    prefix_path:          /client
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /Homepage/
  param: { module: home, action: index }
  
default:
  url:   /
  param: { module: sfGuardAuth, action: signin }
  
signout:
  url:   /
  param: { module: sfGuardAuth, action: signin }
  
sf_guard_forgot_password:
  url:   /request_password
  param: { module: sfGuardForgotPassword, action: index }
