# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /Homepage/
  param: { module: home, action: index }
  
default:
  url:   /
  param: { module: sfGuardAuth, action: signin }
  
signout:
  url:   /
  param: { module: sfGuardAuth, action: signin }
  
#client
client_new:
  url:     /client/new
  param:   { module: client, action: new }
  requirements: { sf_method: get }
  
client_create:
  url:     /client.:sf_format
  class:   sfDoctrineRoute
  options: { model: UserProfile, type: object }
  param:   { module: client, action: create, sf_format: html }
  requirements: { sf_method: post }