<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
    
    /**
     * Returns all clients
     *
 	 * @param $userProfileId integer User Profile Id to find clients
     *
     * @return query The query to return results
     */
	public function getAllClients()
	{
	  $q = Doctrine_Query::create()
	      ->from('sfGuardUser sfgu')
	      ->leftJoin('sfgu.sfGuardUserGroup sfug')
	      ->leftJoin('sfgu.UserProfile up')
	      ->where('sfug.group_id = 3');
	 
	    return $q;

	}
    
    /**
     * Returns all clients associated to a user
     *
 	 * @param $userProfileId integer User Profile Id to find clients
     *
     * @return query The query to return results
     */
	public function getClientsForUser($userProfileId)
	{
	  $q = Doctrine_Query::create()
	      ->from('sfGuardUser sfgu')
	      ->leftJoin('sfgu.sfGuardUserGroup sfug')
	      ->leftJoin('sfgu.UserProfile up')
	      ->where('sfug.group_id = 3')
	      ->where('up.parent_user_profile_id = ?', $userProfileId);
	 
	    return $q;

	}
	
    /**
     * Returns all advisors associated
     *
 	 * @param 
     *
     * @return query The query to return results
     */
	public function getAllAdvisors()
	{
	  $q = Doctrine_Query::create()
	      ->from('sfGuardUser sfgu')
	      ->leftJoin('sfgu.sfGuardUserGroup sfug')
	      ->leftJoin('sfgu.UserProfile up')
	      ->where('sfug.group_id = 2');
	 
	    return $q;

	}
	
    /**
     * Returns all advisors associated to a user
     *
 	 * @param $userProfileId integer User Profile Id to find clients
     *
     * @return query The query to return results
     */
	public function getAdvisorsForUser($userProfileId)
	{
	  $q = Doctrine_Query::create()
	      ->from('sfGuardUser sfgu')
	      ->leftJoin('sfgu.sfGuardUserGroup sfug')
	      ->leftJoin('sfgu.UserProfile up')
	      ->where('sfug.group_id = 2')
	      ->where('up.parent_user_profile_id = ?', $userProfileId);
	 
	    return $q;

	}
}