generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          advisor
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
       display: [ first_name, last_name, email_address]
       title: 'Advisor'
       table_method: retrieveAdvisorsForParent
      filter:
        class: false
      form:
        class:     BackendAdvisorForm
      edit:    ~
      new:     ~
