generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MarketData
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          market_data
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
       display: [ id, uploaded_at, inception_date, created_at ]
      filter:  
       class:   false
      form:    ~
      edit:    ~
      new:     ~
