generator:
  class: sfDoctrineGenerator
  param:
    model_class:           UserProfile
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user_profile
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
       display: [ idnumber, name, surname]
       title: '<h2>User Profiles</h2>'
      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     ~