generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Quote
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          quote
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        fields:
        display: [client_id, created_by, created_at]
        title: Quote Management
      filter:  
        display: [client_id,  created_at]
      form:    
        class:          BackendQuoteForm
      edit:    ~
      new:     ~
