generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:   '<h2>Users</h2>'
        display: [=username, created_at, last_login]
        max_per_page: 10        
                
      filter:
        class: false
      form:
        class:  FrontendGuyForm
        display:
          "User":                   [first_name, last_name, email_address, username, password]
          "Profile":                [Userprofile]

      edit:
        title: '<h3>Editing User "%%username%%"</h3>'

      new:
        title: New User