soap:
  list: { parameter: [token], result: { class: ckPropertyResultAdapter, param: { property: result } } }
  create: { parameter: [arrRequests], result: { class: ckPropertyResultAdapter, param: { property: result } } }
  show: { parameter: [token], result: { class: ckPropertyResultAdapter, param: { property: result } } }
