soap:
  create: { parameter: [token], result: { class: ckPropertyResultAdapter, param: { property: result } } }
  new: { parameter: [token], result: { class: ckPropertyResultAdapter, param: { property: result } } }
