all:
  soap: { authenticate: { parameter: [token, username, password], result: { class: ckPropertyResultAdapter, param: { property: result } } } }
soap:
  authenticate: { parameter: [token, username, password], result: { class: ckPropertyResultAdapter, param: { property: result } } }
  new: { parameter: [token, username, password], result: { class: ckPropertyResultAdapter, param: { property: result } } }
